name: Pipeline

on:
  push:
    branches:
      - 'master'
      - 'feature**'

env:
  TEMPLATE_NAME: template.yaml
  TESTING_S3_BUCKET: jokes-ui-test
  TESTING_STACK_NAME: jokes-ui-test
  PROD_S3_BUCKET: jokes-ui
  PROD_STACK_NAME: jokes-ui

jobs:
  test:
    name: Run unit tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install NPM 8
        run: npm install -g npm@8

      - name: Install and audit packages
        run: npm ci
        env:
          NODE_ENV: test
      - name: Run tests
        run: npm run test

  build-and-deploy-feature:
    name: Deploy feature branch
    if: startsWith(github.ref, 'refs/heads/feature')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install NPM 8
        run: npm install -g npm@8
      - name: Build Gatsby site
        run: npm run build
        env:
          DEVELOPMENT: true
          NODE_ENV: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy test infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.TESTING_STACK_NAME }}
          template: ${{ env.TEMPLATE_NAME }}
          no-fail-on-empty-changeset: 1
          parameter-overrides: 'AccountId=${{ secrets.AWS_ACCOUNT_ID }},Environment=test'
      - name: Copy static site to test S3 bucket
        run: ./scripts/copyToS3.sh ${TESTING_S3_BUCKET}

  deploy-testing:
    name: Deploy to test environment
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install NPM 8
        run: npm install -g npm@8
      - name: Build Gatsby site
        run: npm run build
        env:
          DEVELOPMENT: true
          NODE_ENV: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy test infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.TESTING_STACK_NAME }}
          template: ${{ env.TEMPLATE_NAME }}
          no-fail-on-empty-changeset: 1
          parameter-overrides: 'AccountId=${{ secrets.AWS_ACCOUNT_ID }},Environment=test'
      - name: Copy static site to test S3 bucket
        run: ./scripts/copyToS3.sh ${{ env.TESTING_S3_BUCKET }}

  deploy-production:
    name: Deploy to production
    if: github.ref == 'refs/heads/master'
    needs: [deploy-testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install NPM 8
        run: npm install -g npm@8
      - name: Build Gatsby site
        run: npm run build
        env:
          NODE_ENV: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy production infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.PROD_STACK_NAME }}
          template: ${{ env.TEMPLATE_NAME }}
          no-fail-on-empty-changeset: 1
          parameter-overrides: 'AccountId=${{ secrets.AWS_ACCOUNT_ID }}'
      - name: Copy static site to production S3 bucket
        run: ./scripts/copyToS3.sh ${{ env.PROD_S3_BUCKET }}

  bump:
    name: Bump the version number and tag the commit
    needs: [deploy-production]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install NPM 8
        run: npm install -g npm@8

      - name: Set git name and email
        run: |
          git config --local user.email "dbowland1+bot@gmail.com"
          git config --local user.name "github-actions[bot]"
      - name: Bump the minor version
        run: npm version minor
      - name: Push tag created by version bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
